### ISSUE TITLE
requirements指明版本号

### ISSUE THREAD

**Issue by duoduo369** [python-cn/firefly#43]
pip install 后尝试启动发现报错，看了下requirements并没有指定具体版本。

    from flask_redis import FlaskRedis
    ImportError: cannot import name FlaskRedis

**Comment by dongweiming** [comment]
@duoduo369 是直接`pip install -r requirements.txt`么?

**Comment by dongweiming** [comment]
@duoduo369  https://github.com/python-cn/firefly/pull/24 看看是不是对你有帮助

**Comment by dongweiming** [comment]
按说不指定版本应该安装最新版

**Comment by duoduo369** [comment]
我之前用的豆瓣源 版本有些问题 改成默认的源upgrade了ok了

**Comment by orangle** [comment]
是版本的问题？

**Comment by dongweiming** [comment]
@orangle 是因为使用豆瓣的pypi.
