### ISSUE TITLE
Whether to remove JsonMixin ?

### ISSUE THREAD

**Issue by halfcrazy** [python-cn/firefly#46]
As flask-restful has a built-in method called marshal, which has the similar function like JsonMixin does.
marshal filters the properties with a specify format, and transform the input data into a OrderedDict.

**Comment by dongweiming** [comment]
I think you can use a specify format with dict instead of OrderedDict. and remove JsonMixin

**Comment by halfcrazy** [comment]
@dongweiming The marshal default behaviour is to turn the data into a OrderedDict, so if needed to turn it into a dict, we have do extra effort. Otherwise i have to override the built-in marshal method.

**Comment by dongweiming** [comment]
i just read the source code. i found this:
```python
$python manage.py shell

In [1]: from firefly.models import topic

In [2]: post = topic.Post.objects.all()[0]

In [3]: post
Out[3]: <Post: 美好的测试>

In [4]: import json

In [5]: json.loads(post.to_json())
Out[5]: 
{u'_cls': u'Post',
 u'_id': 1,
 u'comments': [1],
 u'content': u"# title\n\u200b\n```python\nprint 'hello'\n```",
 u'created_at': {u'$date': 1429626675779},
 u'title': u'\u7f8e\u597d\u7684\u6d4b\u8bd5',
 u'views': 37}

In [6]: post.to_mongo().to_dict()
Out[6]: 
{'_cls': 'Post',
 '_id': 1,
 'comments': [1],
 'content': u"# title\n\u200b\n```python\nprint 'hello'\n```",
 'created_at': datetime.datetime(2015, 4, 21, 14, 31, 15, 779000),
 'title': u'\u7f8e\u597d\u7684\u6d4b\u8bd5',
 'views': 37}
```

so . `JsonMixin` don't need to exist

**Comment by halfcrazy** [comment]
@dongweiming TIL

**Comment by dongweiming** [comment]
or we can use extend a new class with a `to_dict` method. for  example:

```python

def update_db(db):
    def to_dict(self):
       return self.to_mongo().to_dict()
    setattr(db.Document, 'to_dict', to_dict)
db = MongoEngine(app) 
update_db(db)
```

**Comment by halfcrazy** [comment]
@dongweiming  Good idea.
