### ISSUE TITLE
环境问题？

### ISSUE THREAD

**Issue by duoduo369** [python-cn/firefly#71]
按照(firefly新手引导)[http://python-cn.org/#/post/new.md]装完环境，编译完静态文件后出了一波js报错
mac windows下chrome firefox都是这样

![qq 20150507132714](https://cloud.githubusercontent.com/assets/6789022/7508980/393a8780-f4bd-11e4-9d2f-62bbc3884e87.png)
![qq 20150507132645](https://cloud.githubusercontent.com/assets/6789022/7508981/393c9516-f4bd-11e4-92c1-eea010dfbfd9.png)

**Comment by duoduo369** [comment]
貌似是require js或者什么地方的引用问题 我分别在这两个地方添加了codemirror.js错误才没有

    static/javascripts/components/lib/codemirror.js
    firefly/static/javascripts/components/codemirror/lib/codemirror.js

好像是gitignore把 `lib/` 的东西忽略了没有提交上来

**Comment by halfcrazy** [comment]
@duoduo369 确实是gitignore的原因被忽略了，在gitignore最后用!语法补上吧

**Comment by duoduo369** [comment]
@halfcrazy 问题是是否还有其他的什么js也一块被ignore了我看github上codemirror这个js里面比firefly里面的东西要多一些文件夹
