### ISSUE TITLE
建议加上Github登录的功能

### ISSUE THREAD

**Issue by startover** [python-cn/firefly#89]
类似[CNode](https://cnodejs.org/)社区的Github登录，个人感觉比较方便～

**Comment by halfcrazy** [comment]
@startover 见https://github.com/python-cn/flask-social-blueprint Github会支持的

**Comment by startover** [comment]
我是看TODO List没有...感谢回复～

**Comment by halfcrazy** [comment]
@startover 嗯，这个包本身带了Facebook Twitter Github Google，我们添加了 豆瓣，QQ 和微博的。

**Comment by startover** [comment]
@halfcrazy 了解～这个隐藏的比较深，刚开始没看到^_^
